version: '3'
services:
    db:
      image: mysql:8.0.27
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: tomoki1823
        MYSQL_DATABASE: memory_share
        MYSQL_USER: maousmud
        MYSQL_PASSWORD: tomoki1823
        TZ: 'Asia/Tokyo'
      volumes:
        - mysql_data:/var/lib/mysql
volumes:
  mysql_data: